stages:
  - test
  - deploy

image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/archlinux:base-devel

test:
  stage: test
  tags:
    - x86_64-linux-kvm-docker
  script:
    - pacman -Syu --noconfirm --needed dbus rust gsettings-desktop-schemas clang speech-dispatcher cargo-tarpaulin
    - dbus-run-session cargo tarpaulin --out xml --engine llvm
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

fmt:
  stage: test
  tags:
    - x86_64-linux-kvm-docker
  script:
    - pacman -Syu --noconfirm --needed rust
    - cargo fmt --check

clippy:
  stage: test
  tags:
    - x86_64-linux-kvm-docker
  script:
    - pacman -Syu --noconfirm --needed rust clang speech-dispatcher
    - cargo clippy -- -Dwarnings
    - cargo clippy --tests -- -Dwarnings

proxy:
  stage: test
  tags:
    - x86_64-linux-kvm-docker
  script:
    - pacman -Syu --noconfirm --needed rust git zbus_xmlgen
    - cd steamos-manager-proxy/src
    - ./update_proxy.sh
    - git status
    - git diff
    - git diff-index --quiet HEAD

build:
  stage: deploy
  tags:
    - x86_64-linux-kvm-docker
  script:
    - pacman -Syu --noconfirm --needed dbus rust gsettings-desktop-schemas clang speech-dispatcher
    - make install DESTDIR=build
    - tar --zstd -C build -cvf build.tar.zst .
  artifacts:
    paths:
      - build.tar.zst
