//! # D-Bus interface proxy for: `com.steampowered.SteamOSManager1.CpuScheduler1`
//!
//! This code was generated by `zbus-xmlgen` `5.3.0` from D-Bus introspection data.
//! Source: `com.steampowered.SteamOSManager1.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "com.steampowered.SteamOSManager1.CpuScheduler1",
    default_service = "com.steampowered.SteamOSManager1",
    default_path = "/com/steampowered/SteamOSManager1",
    assume_defaults = true
)]
pub trait CpuScheduler1 {
    /// AvailableCpuSchedulers property
    #[zbus(property)]
    fn available_cpu_schedulers(&self) -> zbus::Result<Vec<String>>;

    /// CpuScheduler property
    #[zbus(property)]
    fn cpu_scheduler(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_cpu_scheduler(&self, value: &str) -> zbus::Result<()>;
}
