//! # D-Bus interface proxy for: `com.steampowered.SteamOSManager1.PerformanceProfile1`
//!
//! This code was generated by `zbus-xmlgen` `5.3.0` from D-Bus introspection data.
//! Source: `com.steampowered.SteamOSManager1.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "com.steampowered.SteamOSManager1.PerformanceProfile1",
    default_service = "com.steampowered.SteamOSManager1",
    default_path = "/com/steampowered/SteamOSManager1",
    assume_defaults = true
)]
pub trait PerformanceProfile1 {
    /// AvailablePerformanceProfiles property
    #[zbus(property)]
    fn available_performance_profiles(&self) -> zbus::Result<Vec<String>>;

    /// PerformanceProfile property
    #[zbus(property)]
    fn performance_profile(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_performance_profile(&self, value: &str) -> zbus::Result<()>;

    /// SuggestedDefaultPerformanceProfile property
    #[zbus(property)]
    fn suggested_default_performance_profile(&self) -> zbus::Result<String>;
}
