//! # D-Bus interface proxy for: `com.steampowered.SteamOSManager1.ScreenReader1`
//!
//! This code was generated by `zbus-xmlgen` `5.3.0` from D-Bus introspection data.
//! Source: `com.steampowered.SteamOSManager1.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "com.steampowered.SteamOSManager1.ScreenReader1",
    default_service = "com.steampowered.SteamOSManager1",
    default_path = "/com/steampowered/SteamOSManager1",
    assume_defaults = true
)]
pub trait ScreenReader1 {
    /// GetVoices method
    fn get_voices(&self) -> zbus::Result<Vec<String>>;

    /// GetVoicesForLocale method
    fn get_voices_for_locale(&self, locale: &str) -> zbus::Result<Vec<String>>;

    /// TriggerAction method
    fn trigger_action(&self, action: &str, timestamp: u64) -> zbus::Result<()>;

    /// Enabled property
    #[zbus(property)]
    fn enabled(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_enabled(&self, value: bool) -> zbus::Result<()>;

    /// Mode property
    #[zbus(property)]
    fn mode(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_mode(&self, value: &str) -> zbus::Result<()>;

    /// Pitch property
    #[zbus(property)]
    fn pitch(&self) -> zbus::Result<f64>;
    #[zbus(property)]
    fn set_pitch(&self, value: f64) -> zbus::Result<()>;

    /// Rate property
    #[zbus(property)]
    fn rate(&self) -> zbus::Result<f64>;
    #[zbus(property)]
    fn set_rate(&self, value: f64) -> zbus::Result<()>;

    /// Voice property
    #[zbus(property)]
    fn voice(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_voice(&self, value: &str) -> zbus::Result<()>;

    /// VoiceLocale property
    #[zbus(property)]
    fn voice_locale(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_voice_locale(&self, value: &str) -> zbus::Result<()>;

    /// VoiceLocales property
    #[zbus(property)]
    fn voice_locales(&self) -> zbus::Result<Vec<String>>;

    /// Volume property
    #[zbus(property)]
    fn volume(&self) -> zbus::Result<f64>;
    #[zbus(property)]
    fn set_volume(&self, value: f64) -> zbus::Result<()>;
}
